import { registerSW } from 'virtual:pwa-register';
import { pwaUpdateState } from './updateState';

/**
 * Register the app's service worker (production builds only). The worker is
 * generated by `vite-plugin-pwa` with `registerType: 'prompt'`: a new build is
 * never activated behind the writer's back — multiple tabs share one origin and
 * a silent swap would leave them on mixed chunk versions mid-session. Instead,
 * `onNeedRefresh` raises `pwaUpdateState`, the banner offers a reload, and only
 * that explicit choice activates the waiting worker.
 */
export const registerPwa = (): void => {
  if (import.meta.env.DEV) return;
  if (!('serviceWorker' in navigator)) return;
  const updateServiceWorker = registerSW({
    onNeedRefresh: () => {
      pwaUpdateState.setApplyCallback(() => {
        void updateServiceWorker(true);
      });
      pwaUpdateState.set(true);
    },
  });
};
